export const menu = [
    {
        id: 1,
        category: 'vegetarian',
        title: 'mama margherita',
        image: 'y',
        base: 'homestyle tomato sauce',
        toppings: ['tomato', 'mozzarella slices', 'fresh basil'],
        price: '14.99',
        bestseller: false,
        vegetarian: true,
        spicy: false,
    },
    {
        id: 2,
        category: 'vegetarian',
        title: 'plant daddy',
        image: 'y',
        base: 'house-made pesto',
        toppings: ['tomato', 'mushrooms', 'black olives', 'green peppers','mozzarella cheese'],
        price: '16.99',
        bestseller: true,
        vegetarian: true,
        spicy: false,
    },
    {
        id: 3,
        category: 'vegetarian',
        title: 'the vegan one',
        image: 'y',
        base: 'bbq sauce',
        toppings: ['mushrooms', 'green peppers', 'vegan chkn', 'hot peppers'],
        price: '16.99',
        bestseller: false,
        vegetarian: true,
        spicy: true,
    },
    {
        id: 4,
        category: 'vegetarian',
        title: 'fresh to death',
        image: 'y',
        base: 'homestyle tomato sauce',
        toppings: ['mushrooms', 'pineapple', 'tomato', 'black olives', 'mozzarella cheese', 'cilantro'],
        price: '16.99',
        bestseller: false,
        vegetarian: true,
        spicy: false,
    },
    {
        id: 5,
        category: 'classics',
        title: 'pepperoni please',
        image: 'y',
        base: 'homestyle tomato sauce',
        toppings: ['pepperoni', 'mozzarella slices'],
        price: '14.99',
        bestseller: false,
        vegetarian: false,
        spicy: false,
    },
    {
        id: 6,
        category: 'vegetarian',
        title: 'McCreamy',
        image: 'y',
        base: 'creamy roasted garlic sauce',
        toppings: ['mozzarella cheese', 'cheddar cheese'],
        price: '14.99',
        bestseller: true,
        vegetarian: false,
        spicy: false,
    },
    {
        id: 7,
        category: 'classics',
        title: 'Hawaii High-Five',
        image: 'y',
        base: 'homestyle tomato sauce',
        toppings: ['pineapple', 'mushrooms', 'smoked ham', 'cheddar cheese'],
        price: '16.99',
        bestseller: true,
        vegetarian: false,
        spicy: false,
    },
    {
        id: 8,
        category: 'classics',
        title: 'Meat Street',
        image: 'y',
        base: 'bbq sauce',
        toppings: ['pepperoni', 'sausage', 'smoked ham', 'cheddar cheese'],
        price: '16.99',
        bestseller: false,
        vegetarian: false,
        spicy: false,
    },
    {
        id: 9,
        category: 'classics',
        title: 'deluxxxe',
        image: 'y',
        base: 'homestyle tomato sauce',
        toppings: ['green pepper', 'tomato', 'mushrooms', 'pepperoni', 'mozzarella cheese', 'hot peppers', 'chili flakes'],
        price: '16.99',
        bestseller: true,
        vegetarian: false,
        spicy: true,
    },
    {
        id: 10,
        category: 'classics',
        title: 'Meat Street',
        image: 'y',
        base: 'bbq sauce',
        toppings: ['pepperoni', 'sausage', 'smoked ham', 'cheddar cheese'],
        price: '16.99',
        bestseller: true,
        vegetarian: false,
        spicy: false,
    },
]