import mamaMargherita from '../images/mama-margherita.svg'
import plantDaddy from '../images/plant-daddy.svg'
import theVeganOne from '../images/the-vegan-one.svg'
import freshToDeath from '../images/fresh-to-death.svg'
import mcCreamy from '../images/mccreamy.svg'
import pepperoniPlease from '../images/pepperoni-please.svg'
import hawaiiHighFive from '../images/hawaii-high-five.svg'
import meatStreet from '../images/meat-street.svg'
import deluxxe from '../images/deluxxxe.svg'
import hamSandwich from '../images/ham-sandwich.svg'
import pizza from '../images/pizza.svg'

const menu = [
    {
        id: 1,
        category: 'vegetarian',
        title: 'mama margherita',
        image: `${mamaMargherita}`,
        sauce: 'homestyle tomato sauce',
        toppings: ['tomato', 'mozzarella slices', 'fresh basil'],
        price: '14.99',
        bestseller: false,
        vegetarian: true,
        spicy: false,
        amount: 1,
    },
    {
        id: 2,
        category: 'vegetarian',
        title: 'plant daddy',
        image: `${plantDaddy}`,
        sauce: 'house-made pesto',
        toppings: ['tomato', 'mushrooms', 'black olives', 'green peppers','mozzarella cheese'],
        price: '16.99',
        bestseller: true,
        vegetarian: true,
        spicy: false,
        amount: 1,
    },
    {
        id: 3,
        category: 'vegetarian',
        title: 'the vegan one',
        image: `${theVeganOne}`,
        sauce: 'BBQ sauce',
        toppings: ['mushrooms', 'green peppers', 'vegan chkn', 'hot peppers'],
        price: '16.99',
        bestseller: false,
        vegetarian: true,
        spicy: true,
        amount: 1,
    },
    {
        id: 4,
        category: 'vegetarian',
        title: 'fresh to death',
        image: `${freshToDeath}`,
        sauce: 'homestyle tomato sauce',
        toppings: ['mushrooms', 'pineapple', 'tomato', 'black olives', 'mozzarella cheese', 'cilantro'],
        price: '16.99',
        bestseller: false,
        vegetarian: true,
        spicy: false,
        amount: 1,
    },
    {
        id: 5,
        category: 'classics',
        title: 'pepperoni please',
        image: `${pepperoniPlease}`,
        sauce: 'homestyle tomato sauce',
        toppings: ['pepperoni', 'mozzarella slices'],
        price: '14.99',
        bestseller: false,
        vegetarian: false,
        spicy: false,
        amount: 1,
    },
    {
        id: 6,
        category: 'vegetarian',
        title: 'McCreamy',
        image: `${mcCreamy}`,
        sauce: 'creamy roasted garlic sauce',
        toppings: ['mozzarella cheese', 'cheddar cheese'],
        price: '14.99',
        bestseller: true,
        vegetarian: true,
        spicy: false,
        amount: 1,
    },
    {
        id: 7,
        category: 'classics',
        title:"hawai'i high-five",
        image: `${hawaiiHighFive}`,
        sauce: 'homestyle tomato sauce',
        toppings: ['pineapple', 'mushrooms', 'smoked ham', 'cheddar cheese'],
        price: '16.99',
        bestseller: true,
        vegetarian: false,
        spicy: false,
        amount: 1,
    },
    {
        id: 8,
        category: 'classics',
        title: 'meat street',
        image: `${meatStreet}`,
        sauce: 'BBQ sauce',
        toppings: ['pepperoni', 'sausage', 'smoked ham', 'cheddar cheese'],
        price: '16.99',
        bestseller: false,
        vegetarian: false,
        spicy: false,
        amount: 1,
    },
    {
        id: 9,
        category: 'classics',
        title: 'deluxxxe',
        image: `${deluxxe}`,
        sauce: 'homestyle tomato sauce',
        toppings: ['green pepper', 'tomato', 'mushrooms', 'pepperoni', 'mozzarella cheese', 'hot peppers', 'chili flakes'],
        price: '16.99',
        bestseller: true,
        vegetarian: false,
        spicy: true,
        amount: 1,
    },
    {
        id: 10,
        category: 'classics',
        title: 'Ham Sandwich',
        image: `${hamSandwich}`,
        sauce: 'house-made pesto',
        toppings: ['black olives', 'smoked ham', 'mozzarella slices'],
        price: '16.99',
        bestseller: true,
        vegetarian: false,
        spicy: false,
        amount: 1,
    },
    {
        id: 11,
        category: 'custom',
        title: 'make your own',
        image: `${pizza}`,
        sauce: '',
        toppings: [],
        price: '9.99',
        bestseller: false,
        vegetarian: false,
        spicy: false,
        amount: 1,
    },
]

export default menu;