import tomatoSauce from '../images/tomato-sauce.svg'
import bbqSauce from '../images/bbq-sauce.svg'
import pestoSauce from '../images/pesto-sauce.svg'
import whiteSauce from '../images/white-sauce.svg'
import cheddarCheese from '../images/cheddar-cheese.svg'
import mozzaCheese from '../images/mozza-cheese.svg'
import mozzaSlices from '../images/mozza-slices.svg'
import mushrooms from '../images/mushrooms.svg'
import blackOlives from '../images/black-olives.svg'
import greenPeppers from '../images/green-peppers.svg'
import pineapple from '../images/pineapple.svg'
import tomato from '../images/tomato.svg'
import pepperoni from '../images/pepperoni.svg'
import smokedHam from '../images/ham.svg'
import sausage from '../images/sausage.svg'
import veganChkn from '../images/vegan-chkn.svg'
import basil from '../images/basil.svg'
import hotPeppers from '../images/hot-peppers.svg'
import cilantro from '../images/cilantro.svg'
import chiliFlakes from '../images/chili-flakes.svg'

const toppings = [
    {
        id: 1,
        category:'sauce',
        title: 'homestyle tomato sauce',
        price: 1.00,
        image: `${tomatoSauce}`,
        vegetarian: true,
        spicy: false,
        checked: false,
        amount: 1,
    },
    {
        id: 2,
        category:'sauce',
        title: 'BBQ sauce',
        price: 1.00,
        image: `${bbqSauce}`,
        vegetarian: true,
        spicy: false,
        checked: false,
        amount: 1,
    },
    {
        id: 3,
        category:'sauce',
        title: 'house-made pesto',
        price: 1.00,
        image: `${pestoSauce}`,
        vegetarian: true,
        spicy: false,
        checked: false,
        amount: 1,
    },
    {
        id: 4,
        category:'sauce',
        title: 'creamy roasted garlic',
        price: 1.00,
        image: `${whiteSauce}`,
        vegetarian: true,
        spicy: false,
        checked: false,
        amount: 1,
    },
    {
        id: 5,
        category:'cheese',
        title: 'cheddar cheese',
        price: 2.00,
        image: `${cheddarCheese}`,
        vegetarian: true,
        spicy: false,
        checked: false,
        amount: 1,
    },
    {
        id: 6,
        category:'cheese',
        title: 'mozzarella cheese',
        price: 2.00,
        image: `${mozzaCheese}`,
        vegetarian: true,
        spicy: false,
        checked: false,
        amount: 1,
    },
    {
        id: 7,
        category:'cheese',
        title: 'mozzarella slices',
        price: 2.00,
        image: `${mozzaSlices}`,
        vegetarian: true,
        spicy: false,
        checked: false,
        amount: 1,
    },
    {
        id: 8,
        category:'veggies',
        title: 'mushrooms',
        price: 1.00,
        image: `${mushrooms}`,
        vegetarian: true,
        spicy: false,
        checked: false,
        amount: 1,
    },
    {
        id: 9,
        category:'veggies',
        title: 'black olives',
        price: 1.00,
        image: `${blackOlives}`,
        vegetarian: true,
        spicy: false,
        checked: false,
        amount: 1,
    },
    {
        id: 10,
        category:'veggies',
        title: 'green peppers',
        price: 1.00,
        image: `${greenPeppers}`,
        vegetarian: true,
        spicy: false,
        checked: false,
        amount: 1,
    },
    {
        id: 11,
        category:'veggies',
        title: 'pineapple',
        price: 1.00,
        image: `${pineapple}`,
        vegetarian: true,
        spicy: false,
        checked: false,
        amount: 1,
    },
    {
        id: 12,
        category:'veggies',
        title: 'tomato',
        price: 1.00,
        image: `${tomato}`,
        vegetarian: true,
        spicy: false,
        checked: false,
        amount: 1,   
    },
    {
        id: 13,
        category:'protein',
        title: 'pepperoni',
        price: 2.00,
        image: `${pepperoni}`,
        vegetarian: false,
        spicy: false,
        checked: false,
        amount: 1,
    },
    {
        id: 14,
        category:'protein',
        title: 'smoked ham',
        price: 2.00,
        image: `${smokedHam}`,
        vegetarian: false,
        spicy: false,
        checked: false,
        amount: 1,
    },
    {
        id: 15,
        category:'protein',
        title: 'sausage',
        price: 2.00,
        image: `${sausage}`,
        vegetarian: false,
        spicy: false,
        checked: false,
        amount: 1,
    },
    {
        id: 16,
        category:'protein',
        title: 'vegan chkn',
        price: 2.00,
        image: `${veganChkn}`,
        vegetarian: true,
        spicy: false,
        checked: false,
        amount: 1,
    },
    {
        id: 17,
        category:'garnish',
        title: 'fresh basil',
        price: 0.75,
        image: `${basil}`,
        vegetarian: true,
        spicy: false,
        checked: false,
        amount: 1,
    },
    {
        id: 18,
        category:'garnish',
        title: 'hot peppers',
        price: 0.75,
        image: `${hotPeppers}`,
        vegetarian: true,
        spicy: true,
        checked: false,
        amount: 1,
    },
    {
        id: 19,
        category:'garnish',
        title: 'cilantro',
        price: 0.75,
        image: `${cilantro}`,
        vegetarian: true,
        spicy: false,
        checked: false,
        amount: 1,
    },
    {
        id: 20,
        category:'garnish',
        title: 'chili flakes',
        price: 0.75,
        image: `${chiliFlakes}`,
        vegetarian: true,
        spicy: true,
        checked: false,
        amount: 1,
    },
]

export default toppings;