export const toppings = [
    {
        id: 1,
        category:'veggies',
        title: 'mushrooms',
        price: 0.50,
        image: 'y',
    },
    {
        id: 2,
        category:'veggies',
        title: 'black olives',
        price: 0.50,
        image: 'y',

    },
    {
        id: 3,
        category:'veggies',
        title: 'green peppers',
        price: 0.50,
        image: 'y',

    },
    {
        id: 4,
        category:'veggies',
        title: 'pineapple',
        price: 0.50,
        image: 'y',
    },
    {
        id: 5,
        category:'veggies',
        title: 'tomato',
        price: 0.50,
        image: 'y',
    },
    {
        id: 6,
        category:'garnish',
        title: 'fresh basil',
        price: 0.30,
        image: 'y',
    },
    {
        id: 7,
        category:'garnish',
        title: 'hot peppers',
        price: 0.30,
        image: 'y',
    },
    {
        id: 8,
        category:'garnish',
        title: 'cilantro',
        price: 0.30,
        image: 'y',
    },
    {
        id: 9,
        category:'garnish',
        title: 'chili flakes',
        price: 0.30,
        image: 'y',
    },
    {
        id: 10,
        category:'protein',
        title: 'pepperoni',
        price: 1.00,
        image: 'y',
    },
    {
        id: 11,
        category:'protein',
        title: 'smoked ham',
        price: 1.00,
        image: 'y',
    },
    {
        id: 12,
        category:'protein',
        title: 'sausage',
        price: 1.00,
        image: 'y',
    },
    {
        id: 13,
        category:'protein',
        title: 'vegan chkn',
        price: 1.00,
        image: 'y',
    },
    {
        id: 14,
        category:'cheese',
        title: 'cheddar cheese',
        price: 1.00,
        image: 'y',
    },
    {
        id: 15,
        category:'cheese',
        title: 'mozzarella cheese',
        price: 1.00,
        image: 'y',
    },
    {
        id: 16,
        category:'cheese',
        title: 'mozzarella slices',
        price: 1.00,
        image: 'y',
    },
    {
        id: 17,
        category:'sauce',
        title: 'homestyle tomato sauce',
        price: 0.50,
        image: 'y',
    },
    {
        id: 18,
        category:'sauce',
        title: 'bbq sauce',
        price: 0.50,
        image: 'y',
    },
    {
        id: 19,
        category:'sauce',
        title: 'house-made pesto',
        price: 0.50,
        image: 'y',
    },
    {
        id: 20,
        category:'sauce',
        title: 'creamy roasted garlic',
        price: 0.50,
        image: 'y',
    },
]